version: '3'

services:
  mongodb:
    build:
      dockerfile: Dockerfile
      context: mongodb
    restart: always
    env_file:
      - backend.env
    volumes:
      - ./seed-data:/seed
  python_api:
    command: /start-reload.sh
    build:
      dockerfile: Dockerfile
      context: python-api
    depends_on:
      - mongodb
    env_file:
      - backend.env
    volumes:
      - ./python-api:/app
    ports:
      - "8000:80"
    stdin_open: true
    tty: true
